widgetti/solara

solara/server/cdn_helper.py, solara/server/starlette.py, tests/unit/cdn_helper_test.py
Because on windows we cached to a file ending in /path.css/__main The mime type was not guessed correctly.
Fixes https://github.com/widgetti/solara/issues/36
=> fix: get correct mime types on windows for cdn proxy.

solara/server/kernel.py, solara/server/patch.py, solara/server/shell.py, tests/unit/shell_test.py
We didn't support the output widget because we didn't implement a shell.
Also, the second commit implement the output widget on the kernel side.
This is similar to what is proposed at https://github.com/jupyter-widgets/ipywidgets/issues/3253#issuecomment-932464163
Related issue that this technique should solve
* https://github.com/jupyter-widgets/ipywidgets/issues/2358
* https://github.com/jupyter-widgets/ipywidgets/issues/3260
=> Feat: output widget support

solara/server/patch.py
`proplot` configures in inline plotting backend on import with ipython magic.
https://github.com/proplot-dev/proplot/blob/d44b25b39f3065d9f603d13416fa5b6c22feb1dd/proplot/config.py#L361
AFAIK the configuration settings does not affect anything when using proplot with solara, but solara's  `FakeIPython` needs to have a fake `magic` method for proplot to be imported. 
Meanwhile, users can monkey patch `FakeIPython`
```python
from solara.server.patch import FakeIPython
FakeIPython.magic = lambda *args: None
```
=> fix proplot import

solara/hooks/misc.py, tests/unit/checkbox_test.py
It does not make sense to trigger on_value when the value passed to use_reactive is changed. This has the side effect of the checkbox' on_value being triggered when the checkbox' value is changed by the code (it should only be triggered when the user clicks the checkbox, or the reactive value is changed by some other part of the code).
@Jhsmit could you test and review this?
=> fix: do not call use_reactive on_value when value is updated externally

solara/website/pages/docs/content/04-tutorial/20-web-app.md
Currently, the code suggestion for the modify script is incorrect. The initial `sol.py` does not use a return a statement. It also use `increment` instead of `on_click` as the event handler. Also, to check for `clicks == 0`, we need to use the state value `clicks.value == 0` instead. Otherwise, nothing happens. I assume this is just a mismatch due to a recent API change.
=> docs: fix modify script code suggestion

solara/components/file_browser.py
This PR adds a boolean `folders_first` to the `FileBrowser`, which makes folders appear first in the sorting.
Also fixes a bug where the default filter for `list_dir` was the default built-in `filter`
=> feat: Allow FileBrowser to show folders first

solara/server/flask.py, tests/integration/flask_test.py
Found when answering https://github.com/widgetti/solara/discussions/106
=> fix: when used under a prefix with flask, strip off the leading root

solara/components/select.py, tests/unit/select_test.py
add disabled keyword to select widgets
see #144
=> feat: add disable keyword to select and select multiple widgets

solara/__main__.py, solara/server/settings.py, solara/test/pytest_plugin.py, solara/website/pages/docs/content/10-howto/50-testing.md
I ran into the same issue as https://github.com/widgetti/solara/issues/112 but when running solara though the pytest framework which means I wasn't able to set the host to 0.0.0.0. This PR adds a way to customize the host with a new environment variable. I thought HOST would be too generic so made it SOLARA_TEST_HOST. I wonder if PORT should be SOLARA_TEST_PORT too?
=> Allow test host to be customized

tests/unit/file_browser_test.py
=> enhancement: modify file bowser unit test to make it easier to understand

solara/server/flask.py, solara/server/settings.py, solara/server/starlette.py
This will let solara work out of the box when the proxy cache dir is not writable, and will not require the user to manually disable the proxy. If the proxy is disabled, the cache dir will not be created and the no endpoint will be registered.
We also notify the user with a warning what happened and how to avoid it.
```
$ solara run sol.py
/Users/maartenbreddels/github/widgetti/solara-copy/solara/server/settings.py:162: UserWarning: Could not create /..../share/solara/cdn due to ..... We will automatically disable the assets proxy for you. If you want to disable this warning, set SOLARA_ASSETS_PROXY to False (e.g. export SOLARA_ASSETS_PROXY=false).
warnings.warn(
```
=> feat: when the proxy cache dir cannot be written to, disable the proxy

solara/server/patch.py, solara/server/shell.py, tests/unit/output_widget_test.py
This implements a subset (only clear_output) of https://github.com/widgetti/solara/pull/132/files which is more trivial to implement and get correct.
See
* https://github.com/ipython/ipykernel/pull/1135
* https://github.com/jupyter-widgets/ipywidgets/pull/3759
* https://github.com/ipython/ipykernel/pull/115/ 
* https://github.com/ipython/ipykernel/pull/1110
=> feat: support IPython clear_output for output widget

solara/autorouting.py, solara/server/app.py
Fixes https://github.com/widgetti/solara/issues/208
We should only have to do this for a .py script run, and set `__name__`. I don't think we should do this for a notebook.
=> fix: module namespace when running as script was not set to __main__

solara/server/starlette.py
The function `spawn_task` was renamed to `start_task_soon` and
was deprecated. We added forward/backward compatibility for this.
However, now the deprecated function is removed in version 4, which
breaks the type checking.
=> ci: fix support for anyio 4 typing

packages/solara-enterprise/solara_enterprise/auth/__init__.py
This happens with the user reactive variable, which got a key like 'None:0'. After a hot reload, the counter for this type was reset, and a different reactive variable got the same key. The value for the user reactive variable was then a dict with the user values.
=> fix: a hot reload could mix reactive variables from solara internal ones

solara/widgets/vue/vegalite.vue
1. notebook: wrong mimetype (see 1st commit)
2. lab: requirejs was not loaded (see 2nd commit)
Fixes the non-colab part of #287
=> fix: make altair work in Jupyter notebook and Jupyter Lab

solara/server/app.py
=> fix: subpackage changes not autoreloaded

.github/workflows/codequality.yaml
Introduced in traitlets 5.10 due to
* https://github.com/ipython/traitlets/pull/868
* https://github.com/ipython/traitlets/pull/818
The correct way would be to fix the errors, but we don't want CI to fail randomly. This also supports our idea of having lockfiles for CI.
=> ci: fix lint failure of mypy due to modern typed libraries

solara/minisettings.py, tests/unit/settings_test.py
Because we did not implement a setter for the settings, command
line arguments were not passed to the jinja template.
Values were set, but .dict() used the _values dict which was
not updated by the setter.
Note that environment variables did work, so although
SOLARA_THEME_VARIANT=dark HOST=localhost solara run ...
Did work, the following did not:
HOST=localhost solara run ... --theme-variant=dark
=> fix: pass settings to the jinja template. 

solara/server/flask.py
It seems the underlying library wsproto is not thread safe. Using a mutex to protect the websocket calls seems to fix the issue.
=> fix: websocket messages using flask were sometimes corrupted.

solara/server/starlette.py
it should just call close on the websocket implementation.
=> fix: starlette websocket close called itself recursively

solara/server/static/main-vuetify.js
Before, we ran the solara component with an empty search query first,
and then updated the search query. This caused a flicker in the UI.
=> fix: pass search query directly to solara

solara/server/templates/solara.html.j2
The fact that this did not affect our code is an indication that we
are not using it internally. Using ipypopout, this bug was found,
because it does use the baseUrl.
=> fix: baseUrl should not be suffixed with /jupyter

solara/test/pytest_plugin.py
Each time the ipywidgets_runner fixture was used, all fixtures are used. This means the ipywidgets_runner_solara runner was also used, causing the solara_test fixture to always run and also close the app each time, which close all the contexts.
This is bad for performance of the tests, but it is possibly also the cause for some flakeyness in our tests.
=> refactor: do not run all runners in ipywidgets_runner fixture

solara/server/app.py
Solara by default assumes the name for `solara run <name>` is a directory. However, when the name is also a package, which imports module from the package, the package modules can be loaded twice. Solara will execute the python files in the directory, while Python will load the python files as modules from the package. This can leads to unexpected behavior, such as reactive variables existing twice.
=> feat: warn user when modules can be loaded twice.

solara/test/pytest_plugin.py
If the test failed once, it will fail all subsequent tests because
it did not do a proper cleanup.
=> fix: make solara_test fixture not fail subsequent tests

packages/solara-widget-manager/src/kernel.ts, solara/scope/__init__.py, solara/server/app.py, solara/server/flask.py, solara/server/kernel.py, solara/server/kernel_context.py, solara/server/patch.py, solara/server/server.py, solara/server/starlette.py, solara/server/telemetry.py, solara/test/pytest_plugin.py, solara/toestand.py, tests/integration/ssg_test.py, tests/unit/app_test.py, tests/unit/conftest.py, tests/unit/no_solara_test.py, tests/unit/output_widget_test.py, tests/unit/patch_test.py, tests/unit/shell_test.py, tests/unit/toestand_test.py
We have been using the jupyter session_id as a unique key for
the ill defined concept of a "AppContext".
For consistency, we now use the kernel_id as the unique key
and renamed the AppContext to VirtualKernelContext.
A VirtualKernelContext is a context manager that
needs to wrap any code that uses a kernel, either explicitly
or implicitly, such as widgets.
=> refactor: use kernel_id instead of session_id

solara/test/pytest_plugin.py
We relied on a global variable to wait for the component to be called,
but this seems to not be very robust. Instead, we pass a unique ID
via a query parameter to not re-use the Event object, and store the
context that we actually use, instead of relying on the last used
context found.
=> test: make test more robust by non using globals and guessing the context

packages/solara-widget-manager/src/manager.ts, solara/server/flask.py, solara/server/kernel.py, solara/server/kernel_context.py, solara/server/server.py, solara/server/settings.py, solara/server/starlette.py, solara/server/static/main-vuetify.js, solara/test/pytest_plugin.py, solara/util.py, tests/integration/lifecycle_test.py, tests/integration/popout_test.py, tests/unit/conftest.py, tests/unit/lifecycle_test.py, tests/unit/output_widget_test.py, tests/unit/patch_test.py, tests/unit/shell_test.py, tests/unit/toestand_test.py
This allows an ipypopout or a similar library to open a new browser
window and show a widget that is already running in the main window.
Note that this is limited to the same browser, because the session_id
is required to be the same. This is a security feature.
=> feat: allow reconnecting to existing kernel and display widget by id

packages/solara-widget-manager/src/manager.ts, solara/server/app.py, solara/server/static/main-vuetify.js, tests/integration/reconnect_test.py
Instead of asking a user to refresh the browser, we let the websocket
reconnect and try to restore the page session.
* Fixes #254
* Fixes #161
=> feat: support reconnecting websocket

solara/lab/components/menu.vue
We now give it inline-block. Ideally, we do not have the parent div. But that would require us to use @click.native which will be a breaking change in vue3.
=> fix: make parent div of activator not display it as block

solara/lab/components/menu.py
Because `on_show_menu` hadn't been set, Python and Vue weren't in sync about the status of a menu being open.
=> fix: strange menu behaviour with some child components

.github/workflows/codequality.yaml, .github/workflows/installation.yml, .github/workflows/integration.yml, .github/workflows/javascript.yaml, .github/workflows/unittest.yml, solara/lab/components/menu.py
Adds a weekly scheduled run to all CI workflows which run on push or PR, which now run each Monday at 06:00 UTC.
A periodically scheduled run can detect errors and warnings appearing in changes in upstream dependencies or the build environment. By having a scheduled run they can be traced back easier to a dependency or environment change, then if they would pop up in a random PR.
=> CI: Run workflows once a week

solara/__main__.py, solara/server/reload.py, solara/website/pages/docs/content/15-reference/80-reloading.md, solara/website/pages/docs/content/20-understanding/50-solara-server.md, solara/website/pages/docs/content/30-deploying/10-self-hosted.md, solara/website/pages/docs/content/90-development/10-setup.md, tests/conftest.py
Before, we had a --dev mode that would auto-restart the server when
files changed. This means that auto restart was connected to dev mode.
Now, by default solara is in development mode, and the --auto-restart
option is separated.
This means that we now have a special --production mode that should
be used in production settings. It will serve users with minimized
JS and CSS and disable project and .vue reloading.
This means --reload (a bad and confusing name) and --dev are now
deprecated, but will behave the same as --auto-reload/-a.
=> refactor: replace --dev with --auto-restart and have a --production mode

solara/server/reload.py
Appearently, a module does not always point to a proper file, as shown in #353 .
Fixes #353
=> fix: only try to watch files that exists

pyproject.toml
Remove the `--disable-warnings` argument from the pytest configuration in `pyproject.toml`.
This will re-enable warmings in the unit and integrations tests, allowing deprecations and future unsupported behaviour to be noticed before they turn into errors.
=> pytest config: remove `--disable-warnings`

solara/test/pytest_plugin.py, solara/website/pages/docs/content/10-howto/50-testing.md
We need this to test a new ipyvue version that might not have a vuetify
version that works. Also, if a non-ipyvuetify based test is run, this
step can be skipped.
=> feat(testing): add option to not load vuetify assets before testing

solara/components/togglebuttons.py, tests/unit/toggle_button_test.py
In the example below, before, we would get the value 'default'
instead of the value `None`.
```
import solara
@solara.component
def Page():
size = solara.use_reactive(None)
print("size", repr(size.value))
with solara.ToggleButtonsSingle(value=size, on_value=size.set):
solara.Button("x-small", value="x-small")
solara.Button("small", value="small")
solara.Button("default", value=None)
solara.Button("large", value="large")
solara.Button("x-large", value="x-large")
```
=> fix: None value in ToggleButtons resulted in Button label value

solara/components/applayout.py, solara/test/pytest_plugin.py, tests/unit/applayout_test.py
Before we had a 'fast path' which did not render the nav drawer and
appbar when not used. This caused a different component tree to be
rendered, which caused a re-render of the entire app.
This also causes our parent div to always be the same, which will
make the app behave more consistently (always 100vh parent).
Fixes #331
=> fix: avoid re-render when using sidebar or appbar

solara/components/applayout.py
Example use case:
This makes it possible to remove the padding from the parent
when you want to do a different background color and not end
end up with a white border.
=> feat: add style and classes to AppLayout component

solara/components/input.py
Previously `on_value` would be triggered whenever enter was pressed or `InputText` lost focus. With this PR we would allow people to modify these events.
=> feat: allow any `update_events` on `InputText`

solara/components/markdown.py
Due to legacy reasons we enabled the emoji plugin from pymdown.
Every time the Markdown object gets created, it will load the
emoji extension and will deep copy the emoji database.
This is about 150kb of data:
len(str(pymdownx.emoji1_db.emoji))
This is not a lot, but it is unnecessary and can be avoided.
=> fix: do not use excessive memory when rendering markdown

solara/server/templates/solara.html.j2, solara/website/components/algolia.vue, solara/website/templates/index.html.j2
We run the initialize of algolia asap now, so it's functional before
hydration.
The problem was that the JS part of the vue template was not executed
before hydration, so the algolia object was not initialized.
=> docs: have search/algolia work before hydration

solara/components/applayout.py, solara/components/title.py
The title change caused a render twice.
=> fix: do not trigger re-render due to unneeded state in context

solara/server/patch.py, tests/unit/display_test.py
We did not attach a display hook to the thread.
Other ways to fix could be to attach a default output instead of using
the display hook.
=> fix: display() did not work in threads

solara/server/settings.py, solara/server/starlette.py
This gives a better performance for starlette.
enable with SOLARA_EXPERIMENTAL_PERFORMANCE=1
=> perf: throttle sending websocket messages

solara/__main__.py, solara/minisettings.py, solara/server/kernel.py, solara/server/reload.py, solara/website/pages/apps/scatter.py, solara/website/pages/doc_use_download.py
Refactor, cleanup and remove old Python 2 and =<3.5 constructs and replace them with modern Python 3.6+ syntax.
- Remove the default subclass (object) when defining a class
- Use New Super syntax ([PEP 3135](https://peps.python.org/pep-3135/))
- Define sets with curly braces `{}` instead of `set()`
- Remove forced `str("native")` literals
- Replace percent-formatted strings by .format() strings
Used [pyupgrade](https://github.com/asottile/pyupgrade) 3.15.0 with `--py36-plus` as starting point for this PR.
=> Refactor Python code with Python 3.6+ features

packages/solara-vuetify-app/package-lock.json, packages/solara-vuetify-app/package.json, packages/solara-vuetify-app/src/empty.js, packages/solara-vuetify-app/webpack.config.js, packages/solara-widget-manager/src/manager.ts, packages/solara-widget-manager8/package-lock.json, packages/solara-widget-manager8/package.json, packages/solara-widget-manager8/patches/@jupyterlab+outputarea+3.6.4.patch, packages/solara-widget-manager8/patches/@jupyterlab+rendermime+3.6.4.patch
This gets rid of React, CodeMirror, blueprint Yjs and other
smaller dependencies that we do not need in solara.
Some of the original dependencies are added back in:
https://github.com/voila-dashboards/voila/pull/481
=> performance: shrink js bundle size by avoiding jupyterlab dependencies

solara/server/server.py, solara/server/templates/solara.html.j2, solara/util.py
We include css and js resources with a p=<hash> parameter to avoid hitting the browser cache and serving old versions of the files.
Small contents <10kb are inlined in the html file.
Should solve: 
* https://github.com/widgetti/solara/discussions/430
* https://github.com/widgetti/solara/discussions/311
* https://github.com/widgetti/solara/issues/425
Closes https://github.com/widgetti/solara/issues/315
=> feat: avoid cache hits when js or css resources change using hash param

solara/website/pages/docs/content/10-howto/ipywidget_libraries.md, solara/website/pages/examples/libraries/ipyleaflet.py, solara/website/pages/examples/libraries/ipyleaflet_advanced.py
`isolation: isolate` is more universal
=> Refactor: ipyleaflet examples used `z-index` instead of `isolation`

solara/components/file_browser.py
Before:
After:
Checked other docstrings, no similar issues.
=> fix: docstring list indent

pyproject.toml, tests/integration/cdn_test.py
I can't say I figured out what broke this
=> fix: solara.server.jupyter.server_extension not activating

pyproject.toml, solara/server/jupyter/server_extension.py
add an alias `_jupyter_server_extension_points` for `_jupyter_server_extension_paths`, as per https://github.com/jupyter-server/jupyter_server/pull/248/commits/0003ade330561981e6bc75a9d32b00b2d34c54fb
=> fix: futureproof jupyter server extension (paths -> points)

solara/server/cdn_helper.py, solara/server/flask.py, solara/server/server.py, solara/server/settings.py, solara/server/starlette.py, solara/settings.py
Based on:
* https://github.com/widgetti/solara/pull/479
* https://github.com/widgetti/solara/pull/480
* https://github.com/widgetti/solara/issues/486
We decided that using the proxy and the cdn if the proxy is not used
is not only something to be used in solara server. In vscode
or colab, we cannot use the proxy, and need to use the cdn directly.
=> refactor: split assets settings in server and non-server parts

solara/server/telemetry.py, solara/settings.py, solara/util.py, solara/widgets/vue/vegalite.vue, solara/widgets/widgets.py, tests/integration/cdn_test.py
By setting SOLARA_ASSETS_PROXY=False, the JS assets will be fetched
directly from the CDN, and not the proxy. This is the default setting
for colab and vscode now, such that Altair works out of the box.
=> fix: support altair in vscode and colab (and more)

solara/__init__.py, solara/scope/__init__.py, solara/website/pages/api/__init__.py, solara/website/pages/api/get_kernel_id.py, solara/website/pages/api/get_session_id.py, solara/website/pages/docs/content/20-understanding/50-solara-server.md, solara/website/pages/examples/general/custom_storage.py
If you want to store data in a custom storage, you need to know the
kernel_id or session_id to scope.
This can be used to implement something similar to reactive variables.
=> feat: get_kernel_id and get_session_id for custom storage

solara/__main__.py
SOLARA_MODE was never used, it was always set by default to 'development'.
=> fix: respect env var SOLARA_MODE in solara cli

solara/components/cross_filter.py, solara/lab/__init__.py, solara/tasks.py, solara/website/pages/api/__init__.py, solara/website/pages/api/task.py, solara/website/pages/api/use_task.py, tests/unit/task_test.py
use_task can replace use_thread, but also support coroutine functions.
task is a decorator that creates a top level task that can be executed
from any location (e.g. a click handler of a button).
=> feat: task and use_task for better asyncio task a thread execution

packages/solara-enterprise/solara_enterprise/ssg.py, solara/__main__.py, solara/server/server.py
We still parsed the raw html at runtime and fed that back into the
jinja template. We now do that as the ssg build phase, which gives
much better performance.
=> performance: pre-render html fully instead of at runtime

solara/lab/utils/cookies.py, solara/lab/utils/headers.py
Sometimes on hot reload, when the value of a user-defined reactive variable is reset, the value would get updated to that of a solara builtin reactive variable. We avoid this here by manually fixing keys for our variables
Should fix https://github.com/widgetti/solara/issues/510 for `solara.lab.cookies/headers`
=> fix: user reactive variables taking on solara builtin variable values on hot reload

.github/workflows/integration.yml
Getting "This site can't be reached":
=> ci: oauth tests do not work with playwright 1.42.0

solara/toestand.py, tests/unit/toestand_test.py
This make the todo app fail, since it would wrap the ref in a reactive
var.
=> fix: reactive ref should be an instance of Reactive to work with use_reactive

solara/components/matplotlib.py, solara/server/app.py, solara/server/patch.py, solara/server/shell.py, solara/website/components/notebook.py, solara/website/pages/examples/general/live_update.py, tests/unit/matplotlib_test.py
feat: improve matplotlib support - as Jupyter
Several improvements:
We do this by checking if the env var 'MPLBACKEND' is not set, and if so, we set it to
module://matplotlib_inline.backend_inline
This makes it behave more like the Jupyter notebook environment.
This makes code that 'just works' in the notebook also work in solara
server. We patch global dicts with scoped dicts.
See #539
=> feat: improve matplotlib support - mimic Jupyter

solara/server/settings.py, solara/server/starlette.py, solara/website/pages/docs/content/20-understanding/50-solara-server.md
Can now be configured using the SOLARA_KERNELS_MAX_COUNT env variable.
=> feat: limit and configure number of virtual kernels to infinite (was 40)

solara/server/patch.py, solara/server/starlette.py, solara/website/pages/docs/content/20-understanding/50-solara-server.md
include threads usage, kernel usage, and memory usage etc.
=> feat: /resourcez endpoint which tracks resource usage

pyproject.toml
Failure was due to us attemting to create a folder called "prefix" in the environment main folder, while a file with the same name is created by pixi.
This PR should fix https://github.com/widgetti/solara/issues/552.
=> fix: installing solara using pixi failing

solara/server/esm.py
This was causing frontend code to sometimes use the old version, and
sometimes the new version. With antd and theming sometimes the theme
would not be applied (antd would probably not recognize the theme object
with from the old antd esm).
=> fix: on hot reload esm modules were created multiple times

solara/autorouting.py, solara/server/app.py, tests/unit/autorouting_test.py, tests/unit/solara_test_apps/single_file_routes.py
Before, if we specified
```python
routes = [
solara.Route(path="/", component=Home, label="Home", layout=Layout),
solara.Route(path="about", component=About, label="About"),
]
```
We would not render the the page and layout correcly.
=> fix: support Layout when specifying routes

solara/autorouting.py, solara/server/app.py
Before we put the internal RenderPage component in the Route.component.
This was not only confusing, but also left no room for using this
field for other purposes, such as using this for a custom Markdown
component.
=> fix: use the Route.component for the real component

.github/workflows/test.yaml
The PRs by @dependabot don't have matching versions of upload and download-artifacts, which makes them fail on CI.
=> chore, ci: Bump upload/download-artifacts to v4

solara/server/app.py, solara/server/kernel_context.py, solara/server/reload.py, solara/website/pages/documentation/api/utilities/on_kernel_start.py, tests/unit/reload_test.py, tests/unit/solara_test_apps/kernel_start.py
Introduced in #471
We should remove the on_kernel_start callbacks on a hot reload, but
not remove the ones added by the hot reload itself.
TODO: What happens when we import packages that are in site-packages that will not be reloaded?
=> fix: on_kernel_start callbacks accumulated after hot reload

solara/server/assets/style.css
If a vue tree gets interrupted (by ipyreact or classic ipywidgets) we start a new (vuetify) app. This causes that root DOM element to take up 100vh, which is only needed for the top-level app.
=> fix: nested vuetify apps should not have 100vh

solara/server/kernel_context.py, solara/server/patch.py, solara/server/settings.py, solara/server/starlette.py, solara/tasks.py, solara/util.py, tests/integration/server_test.py
in pyodide (pycafe) we cannot use threads. We currently have workarounds in pycafe, but it would be easier to just not use threads in the server if they are not available.
=> feat: make the server (starlette) work without threads for pyodide

.github/workflows/test.yaml
Opening this from a fork to properly test the functionality
=> ci: fix `update-ci-package-locks` for PRs opened from a fork

packages/solara-enterprise/solara_enterprise/ssg.py, solara/components/__init__.py, solara/components/file_drop.py, solara/components/file_drop.vue, solara/website/pages/documentation/components/input/file_drop.py
Added multiple file support to file_drop component.  
Same as the original component, directories are simply ignored. Multiple file support was actually embedded in the underlying VUE scripts. I've done minor changes. 
**Compatibility**:
on_file callback function now accepts List[FileInfo] as opposed to single FileInfo object. This may bring some problems for existing codes. As a remedy, if the number of files is just one, we can return a single FileInfo. If not, we return list. I leave it up to you to decide.
This is related to: https://github.com/widgetti/solara/issues/260
=> feat: multiple file support for file_drop

solara/autorouting.py, tests/integration/server_test.py, tests/unit/autorouting_test.py
This broke the website, so we added test now.
Took the opportunity to refactor this to reduce code duplication.
=> fix: autorender did not render child routes

packages/solara-enterprise/solara_enterprise/ssg.py
Previously we attempted to close the playwrights after the threadpool has been closed. However, outside of the async context we only find `pw.browser` (as well as all other properties) to be `None`, which previously resulted in an error due to us asserting that `pw.browser is not None`. Closing the browser and context manager properly should ensure they don't drain any resources after ssg generation is done.
I'm not sure if there is a concern that `close_playwrights` executes before the ssg is done, resulting in the opening of a new context, and that one not being closed.
=> fix: close playwright properly when building ssg

.github/workflows/test.yaml
Although the removal of set_output has been delayed, it will still likely happen at some point. See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for details
=> ci: use env file instead of set_output

.github/workflows/test.yaml
`suo/flake8-github-action` uses Node 12, and `ifaxity/wait-on-action` uses Node 16, actions relying on which are deprecated by Github in favour of Node 20.
=> ci: remove actions that result in deprecation warnings

solara/website/assets/custom.css, solara/website/components/algolia_api.vue
Previously sub-headers in which hits were found were not displayed in the results box. This should guarantee that some header + subheader is displayed. A preview string of the hit is also shown.
=> docs: fix and improve search result display on website

requirements.txt
render.com does not like the editable install.
```
==> Running build command 'pip install -r requirements.txt'...
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /opt/render/project/src
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```
=> ci: requirements.txt without editable mode to deploy to render.com

solara/toestand.py, tests/unit/toestand_test.py
We supported pydantic 1 and 2, using .dict() which was deprecated in pydantic 2.
It is also semantically more correct to use .copy, which in pydantic 2 is model_copy.
We now use copy/model_copy depending on the pydantic version.
=> fix: support pydantic 1 and 2 in reactive vars

solara/server/static/main-vuetify.js
A busy/idle pair of messages is only send when around a websocket message is handled in the main solara-server task.
When the browser location changes, we fade out the main content, which we restore again when the idle message is received. But if we change the location from a thread or task, the busy and idle messages are not send, so the fade out is not restored, leaving the main content faded out.
To solve this we only fade out when the location changes and the kernel is busy.
=> fix: fade out was not restored on navigations from a thread or task

solara/website/pages/documentation/advanced/content/10-howto/30-testing.md, tests/docs/docs_howto_event_with_future_test.py, tests/docs/docs_howto_event_with_polling_test.py, tests/docs/docs_howto_no_browser_api_find_testing_test.py, tests/docs/docs_howto_no_browser_testing_test.py, tests/docs/docs_howto_no_browser_threaded_test.py, tests/unit/file_browser_test.py
We also include an example of how to test if state change happens on the python side when an event happens on the frontend.
The tests in the documentation are also included as real test in the `tests/docs` directory.
=> docs: testing howto includes more examples (including non-browser testing)

solara/website/pages/documentation/advanced/content/30-enterprise/10-oauth.md, solara/website/pages/documentation/getting_started/content/07-deploying/10-self-hosted.md
I had to restructure the nginx configuration example a bit to make it less confusing.
=> docs: explain configuration needed for oauth behind a (nginx) proxy

solara/server/flask.py, solara/server/kernel_context.py, solara/server/starlette.py, tests/integration/lifecycle_test.py, tests/unit/lifecycle_test.py
A kernel could be close multiple times if the websocket was closed at the same time as the close beacon was send. This caused in CI KeyError on custom_storage.py when the kernel cleanup function was called twice.
State managegment for pages is not protected by a mutex, so that it is thread safe.
=> fix: avoid closing a kernel twice by using a mutex

solara/components/datatable.py, solara/lab/hooks/dataframe.py, solara/lab/utils/dataframe.py
working towards https://github.com/widgetti/solara/issues/599
=> refactor API for workign with external dataframe libs

solara/tasks.py, solara/toestand.py, tests/unit/task_test.py
When used in use_task, this can create many keys, which after a next render can be mixed up with a global task.
Now the key include the function name, so it is more unique.
=> fix: more unique keys for tasks to reduce mixup during hot reloads

.github/workflows/test.yaml
Github actions recently upgraded macos latest to be version 14. However, github runners only provides [python 3.11 and 3.12](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md) for this macos version, while the `setup-python` action only provides [python 3.8, 3.9, 3.10](https://github.com/actions/setup-python/issues/852#issuecomment-2077757197) in addition to the default ones.
Previously we were restricting ubuntu to version 20.04 for all python versions. This PR also releases that restriction for python versions other than 3.6, which is [not available for ubuntu 22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md).
=> ci: restrict OS versions when testing on python 3.6

packages/solara-vuetify-app/webpack.config.js
These dependencies were aliased to an empty file to save on bundle size in https://github.com/widgetti/solara/commit/242d7e29bfeeb5ea53bdcfa113bb5caf4626dde9, but turn out to be necessary for the rendering of some mimetypes. Because the aliasing takes place during the minification step, development mode still worked, but running in production mode would show a javascript error.
Fixes https://github.com/widgetti/solara/issues/500.
=> fix: solara.display not working on some mimetypes in production mode

solara/components/markdown.py
Let's pages load even without pymdown-extensions.
Fixes https://github.com/widgetti/solara/issues/617.
=> fix: use default markdown extensions if pymdown-extensions is not installed

.github/workflows/test.yaml
Since I can't replicate the error locally, I'm using this PR to test potential issues.
To test:
Issue turned out to be with the `-X GET` option to `curl`.
Usual response to `curl` is 
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
0 47845    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
date: Wed, 29 May 2024 06:11:26 GMT
0 47845    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
server: uvicorn
content-length: 47845
content-type: text/html; charset=utf-8
set-cookie: solara-session-id=486c5bbc-564a-44[14](https://github.com/widgetti/solara/actions/runs/9281107458/job/25536575550#ste …
```
=> fix(ci): test-install fails on macos with python3.10

solara/server/esm.py, tests/integration/esm_test.py
When we define a esm top level in a module, we don't need to create the module widget. However, if we do this during the running of the app under the context of a virtual kernel, we should directly create the esm widget.
Should fix the failing of https://github.com/widgetti/ipyantd/pull/4
=> fix: support esm define when running under virtual kernel

solara/components/applayout.py
Fixes a bug where, if `solara.lab.Tabs` was the only child of `solara.AppBar`, the `AppBar` would be hidden.
=> fix: show AppBar when Tabs is a child of AppBar

solara/components/details.py, solara/website/pages/documentation/components/layout/details.py
Worked on the issues i was having and commited again.
=> Adding documentation to details component

packages/solara-meta/pyproject.toml
vaex does not support numpy >= 2. We should be able to remove the restriction once vaex is compiled for numpy 2.0.
=> fix(ci): ci fails because of vaex not supporting newest numpy

solara/server/starlette.py
This allows middleware or error handlers to catch the 404 and do something custom.
Example:
```python
import solara
clicks = solara.reactive(0)
added = False
def add_exception_handler():
global added
print("add_exception_handler", added)
if not added:
import solara.server.starlette
from starlette.responses import HTMLResponse
async def server_error(request, exc):
return HTMLResponse(content="My custom 404", status_code=exc.status_code)
solara.server.starlette.app.add_exception_handler(404, server_error)
added = True
@solara.component
def Page():
add_exception_handler()
solara.Text("hello world")
```
=> fix: if we hit a 404 in starlette, raise instead of render a 404

solara/components/input.py, tests/unit/input_test.py
It seems like any of the events used here: https://github.com/vuetifyjs/vuetify/blob/342d75dddb6b85b437bb5b77e8ed0ec35d689b14/packages/vuetify/src/components/VTooltip/VTooltip.ts#L165-L181, i.e. `blur`, `keydown`, and `focus` won't work on children of `ipyvuetify.Tooltip`.
Fixes https://github.com/widgetti/solara/issues/683.
=> fix: InputText blur event not working when used together with tooltip

solara/components/tooltip.py
I noticed a typo in `solara.components.tooltip.Tooltip`, which turned the type annotation into a default value.
Fixes #685
=> fix: typo in `solara.components.tooltip.Tooltip`

solara/lab/components/input_date.py
This change adds a few enhancements to the `InputDate` and `InputDateRange` components:
- Adds support for controlling the minimum/maximum allowed dates.
- Adds support for a date picker that has monthly granularity.
- Adds support for sorting the selected dates (for the `InputDateRange` component only).
See [here](https://github.com/widgetti/solara/issues/653) for the full discussion.
Using the `min_date` and `max_date` parameters to limit selection to dates in the next two weeks:
```python
import datetime as dt
import solara
@solara.component
def Page():
min_date = dt.date.today()
max_date = min_date + dt.timedelta(days=14)
selected_date = solara.use_reactive(min_date)
solara.lab.InputDate(
value=selected_date,
min_date=min_date.isoformat(),
max_date=max_date.isoformat(),
) …
```
=> Feature: InputDate and InputDateRange Enhancements

solara/components/markdown.py
This was broken due to a fix in https://github.com/widgetti/solara/commit/f882941a6a4f76575a0b618c03c049ff39daa2e6 which unbroke client side navigation.
=> fix: no client side navigation for auth/login links

packages/solara-enterprise/solara_enterprise/search/search.vue, solara/components/echarts.vue, solara/components/markdown_editor.vue, solara/components/sql_code.vue, solara/server/templates/solara.html.j2, solara/website/components/algolia_api.vue, solara/widgets/vue/gridlayout.vue, solara/widgets/vue/vegalite.vue
We did not set what was previously named `solara_cdn`. That caused vue template to not use the right cdn when we did not proxy. This also simplied the login, and motivated a rename of getBaseUrl -> getJupyterBaseUrl since that is only used in Jupyter notebook, Lab and Voila.
=> fix: fetch javascript assets correcly when SOLARA_ASSETS_PROXY=False

solara/components/file_browser.py
Fixes #688 
The PR changes the type of paths used internally in `FileBrowser` from `str` to `pathlib.Path` such that the correct parent is always returned.
Also fixed optional kwargs typing
=> fix: FileBrowser bug when navigating to path root

.github/workflows/test.yaml
With `actions-setup-redis@v1.35.0` tests on Ubuntu-20.04 fail because of a missing shared library `libssl.so.3`. Pin version to `v1.24.0` until https://github.com/shogo82148/actions-setup-redis/issues/958 is resolved.
=> ci: downgrade setup-redis action to fix missing shared library

solara/server/patch.py
Normally, setting MPLBACKEND will set the backend because importing matplotlib will set the backend based on this environment variable. However, in the case where matplotlib is imported before solara, such as jdaviz is doing, we need to set the backend manually.
Related: https://github.com/spacetelescope/jdaviz/pull/2909
=> fix: if matplotlib was imported before solara, we set the backend

packages/solara-enterprise/solara_enterprise/auth/starlette.py
settings.main.base_url should have been used, since that can be used to override the base url from starlette.
Note that this should always never be needed once a proxy and uvicorn are configured correctly (see also #745).
But starlette does not respect the x-forwarded-host header, so we might need to use this in the future in situations of proxies that need to set the Host header due to https communication.
Fixes #740
=> fix: to redirect back after auth we used the wrong base url

solara/server/starlette.py
We only checked if the proxy was using https, not if we were using https directly (can be the case via uvicorn)
=> fix: solara could not be embedded in an iframe using https

.pre-commit-config.yaml
To make sure the pre-commit configuration stays up to date, add auto-update schedule to the pre-commit configuration file.
[pre-commit.ci](https://pre-commit.ci/) needs to be enable for this (which I highly recommend). When enabled, it will check once a week if any pre-commit action can be updated, and will open a PR if so.
=> pre-commit: Add auto-update schedule

packages/solara-enterprise/solara_enterprise/search/search.py, packages/solara-enterprise/solara_enterprise/search/search.vue, solara/components/echarts.py, solara/components/echarts.vue, solara/components/markdown.py, solara/components/markdown_editor.py, solara/components/markdown_editor.vue, solara/components/sql_code.py, solara/components/sql_code.vue, solara/widgets/vue/gridlayout.vue, solara/widgets/widgets.py
Fixes https://github.com/widgetti/solara/issues/761.
=> fix: vscode fails to load scripts from _solara/cdn

solara/components/markdown.py
See d875ff5d9a767f738340cfbd674539a8e240e3bd. `startswith` should be `startsWith`.
=> fix: still js console errors from typo in markdown template

.github/workflows/test.yaml
Using `||` means that as long as there is a diff, test automatically pass without running. If there was no diff, all tests would have failed.
=> ci: scheduled test runs pass because of wrong logic operation

.github/workflows/test.yaml
`[ -s ${{ env.DIFF_FILE_LOCATION }} ]` fails, and since we don't catch that in any way the test step would fail.
=> ci: scheduled tests with no dependency changes fail

packages/solara-server/pyproject.toml
This will take us most of the way towards supporting Python 3.13, see https://github.com/widgetti/solara/issues/797 for progress.
=> chore: remove unnecessary version pin from jupyter_client

solara/lab/components/chat.py
Some users have been confused about why the value they give to the `style` prop of `ChatInput` does not get applied to the input field. This makes it possible to style that component.
=> feat: support styling input field of `ChatInput`

solara/components/__init__.py, solara/components/input_text_area.py, solara/website/pages/documentation/components/input/input.py
Fixes https://github.com/widgetti/solara/issues/343
Raw string is required. Otherwise it doesn't accept new characters.
=> feat: add InputTextArea component

solara/server/patch.py
Needed for https://github.com/widgetti/glue-solara/pull/6 to work properly. Otherwise glue cleanup method (https://github.com/glue-viz/glue/blob/e7c2766d85aceea29aae1a51d95d1189f4444b55/glue/viewers/common/viewer.py#L426-L430) fails.
=> feat: add user_ns to our ipython replacement

solara/server/flask.py, solara/server/jupyter/server_extension.py, solara/server/jupyter/solara.py, solara/server/server.py, solara/server/starlette.py, solara/server/static/main-vuetify.js, solara/server/templates/solara.html.j2, tests/integration/server_test.py
Instead of having to rely on voila to display widgets in a popout window, solara itself now can render it. This allows project to drop the dependency on voila.
=> feat: render ipypopout content in jupyter notebook and lab

packages/solara-meta/pyproject.toml, solara/server/templates/solara.html.j2, tests/integration/widget_test.py
This for instance broke ipyaggrid >=0.5.2 due to changes in https://github.com/widgetti/solara/pull/805
=> fix: wrong data-base-url caused chunks and assets in extensions to fail

solara/widgets/vue/navigator.vue
Hash is never included in `window.location.pathname`
=> chore: remove unnecessary checks for location hashes

solara/server/static/main-vuetify.js, solara/website/pages/documentation/advanced/content/20-understanding/40-routing.md, solara/widgets/vue/navigator.vue
Previously this was not officially supported, and would only work when moving within a page, or when initially loading a page with SSG enabled.
=> feat: enable navigation to hashes

solara/server/settings.py, solara/server/templates/loader-solara.html, solara/server/templates/solara.html.j2
See:
https://github.com/widgetti/solara/discussions/673
Use the environiment variable:
SOLARA_THEME_SHOW_BANNER=False
To hide it.
For popout windows we automatically hide it.
=> feat: option to hide banner "This website runs on Solara"

solara/__main__.py, solara/server/qt.py, solara/website/pages/documentation/getting_started/content/00-quickstart.md
Using QtWebEngine to run Solara as a standalone app. This is experimental, and possibly useful for developer that do not like that solara opens in a new browser tab each time. It is also useful for testing before packaging as a standaline binary, see: #724
=> feat: experimental support for running as (qt) app

solara/server/assets/style.css, solara/website/components/sidebar.py, solara/website/pages/__init__.py, solara/website/pages/documentation/examples/__init__.py, solara/website/pages/documentation/examples/ai/chatbot.py, solara/website/pages/documentation/examples/general/vue_component.py, solara/website/pages/documentation/examples/libraries/bqplot.py, solara/website/pages/documentation/examples/libraries/ipyleaflet.py, solara/website/pages/documentation/examples/libraries/ipyleaflet_advanced.py, solara/website/pages/documentation/examples/visualization/annotator.py, solara/website/pages/documentation/examples/visualization/linked_views.py
Because we previously used a `solara.v.NavigationDrawer` with `v_model=True`, that was only hidden and not destroyed on mobile, Vuetify would think that a floating navigation drawer is open on page load. This would mean that the page could not be used before the user tapped somewhere on the page to "close the drawer". Also adds another maximum width restriction to make sure content doesn't become wider than the viewport on mobile resolutions.
=> docs: fixes for mobile users

solara/__main__.py
069a205c88a8cbcb0b0ca23f4d56889c8ad6134a Caused the paths outside of working directory to be the only ones included instead of being excluded
=> fix: wrong condition when determining which files to reload

solara/components/echarts.py, solara/components/echarts.vue, solara/website/pages/documentation/components/viz/echarts.py
Responsive support in solara/component/echarts.py and solara/component/echarts.vue
GIF of the actual resiseable grid layout in action can be found in following issue.
#268
=> fix:Responsive support for echart

solara/_stores.py, solara/hooks/use_reactive.py, solara/reactive.py, solara/settings.py, solara/toestand.py, solara/util.py, solara/website/pages/roadmap/roadmap.md, tests/unit/toestand_test.py
A common source of error is mutation of values in reactive vars. The reactive var cannot notice a change in its value (e.g. a list) if the list is mutated in place.
A user can be mislead that it is working correctly, when another reactive variable triggers a rerender, teaching bad habits.
Detecting mutations in Python without using proxies can be done by making a deepcopy of the object, and comparing the reference to the deepcopy.
This comes at the cost of performance and memory usage, therefore we should enabled this by default in development mode (tests run in this mode by default), so app builders are aware of mistakes while developing.
In production mode we can disable the mutation checks and behave as before.
TODO:
=> feat: detect mutation to values of reactive vars

.github/workflows/test.yaml, packages/pytest-ipywidgets/pyproject.toml, packages/solara-assets/pyproject.toml, packages/solara-enterprise/pyproject.toml, packages/solara-meta/pyproject.toml, packages/solara-server/pyproject.toml, pyproject.toml, solara/template/portal/pyproject.toml
PEP 639 adds support for `license-file` metadata field (see [here](https://discuss.python.org/t/pep-639-round-3-improving-license-clarity-with-better-package-metadata/53020)), which seems to now be the default on PyPI. We need to upgrade hatchling in order for this to be correctly accounted for when releasing, see [this comment](https://github.com/pypa/hatch/issues/1786#issuecomment-2469293644).
=> ci: release process would fail due to old hatchling version

solara/server/flask.py, solara/server/kernel.py, solara/server/starlette.py
Instead of assuming all exceptions are due to a closed connection, we only ignored the exception when it is due to a closed connection.
This caused issues in #841 where we called from the same thread as the websocket's portal, which caused the connection to be ignored without any error message.
=> fix: a failing websocket.send would drop the connection silently

solara/server/kernel.py, solara/server/starlette.py, tests/unit/kernel_test.py
@jfoster17 indeed, what we saw yesterday is a bug in solara. It also explains why you did not see this happening in the notebook.
=> fix: numpy scalars were serialized to a string, instead of a number

solara/server/patch.py
Without this I am running into the following when trying to launch glue-solara:
```
Solara server is starting at http://localhost:8765
Traceback (most recent call last):
File "/home/tom/python/dev/bin/solara", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/tom/Code/solara/solara/__main__.py", line 750, in main
cli(args[1:])
File "/home/tom/python/dev/lib/python3.11/site-packages/rich_click/rich_command.py", line 367, in __call__
return super().__call__(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/tom/python/dev/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/tom/python/dev/lib/python3.11/site-packages/rich_click/rich_command.py", line 152, in main
rv = self.invoke(ctx) …
```
=> Define custom_exceptions on FakeIPython

solara/server/settings.py, solara/server/starlette.py, solara/website/pages/documentation/advanced/content/20-understanding/50-solara-server.md
Following the discussion in #799, I added an option configurable through an environment variable `SOLARA_SESSION_HTTP_ONLY`, and passing this to the `httponly` option in [HTMLResponse](https://www.starlette.io/responses/). 
As discussed, this change is backwards compatible because it defaults to False.
Here we can verify the httpOnly attribute of the `solara-session-id` cookie using Developer tools:
and here's another screenshot showing the behavior when setting the environment variable `SOLARA_SESSION_HTTP_ONLY=True`:
Note that the cookie no longer appears in `document.cookie`. 
Thus, this PR makes it possible for a solara-based application to comply with [cwe 402](https://cwe.mitre.org/data/definitions/402.html)
=> Added a httponly option for HTMLResponse.set_cookie

solara/__main__.py
=> Add timeout to pypi version request, preventing undue hangups on startup

solara/server/app.py, solara/server/flask.py, solara/server/jupyter/server_extension.py, solara/server/patch.py, solara/server/server.py, solara/server/starlette.py, solara/test/pytest_plugin.py, solara/util.py, tests/unit/app_test.py, tests/unit/autorouting_test.py, tests/unit/reload_test.py, tests/unit/toestand_test.py
We now do this after solara.server.starlette is imported, making the starlette app variable accessible from the solara script or module. This makes it easier to add custom endpoints to a solara app.
This will make the script in #841 much simpler, as well as #670
=> refactor: change the order of importing/executing solara script

solara/server/starlette.py
.send_text called .send_bytes
Bug introduced in #400, released since v1.25.0
This showed up when deploying with Modal with the error:
```
Traceback (most recent call last):
File "/pkg/modal/_runtime/container_io_manager.py", line 764, in handle_input_exception
yield
File "/pkg/modal/_container_entrypoint.py", line 210, in run_input_async
await generator_output_task  # Wait to finish sending generator outputs.
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/pkg/synchronicity/async_wrap.py", line 29, in wrapper
return await user_wrapper(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/pkg/synchronicity/async_wrap.py", line 29, in wrapper
return await user_wrapper(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/pkg/synchronicity/async_wrap.py", line 32, in wrapper
raise uc_exc.exc …
```
=> fix: send str using send_bytes in websocket for starlette server

solara/components/datatable.py, solara/lab/hooks/dataframe.py, solara/lab/utils/dataframe.py
Fix for https://github.com/widgetti/solara/issues/526. 
Created a separate variable to store row names to display them correctly as per the index in the loop.
Also, created a new function in utils to cater for getting list of row index names just like for columns.
=> Fixes pandas dataframe transpose display error

solara/lab/components/__init__.py, solara/lab/components/input_time.py, solara/website/pages/documentation/components/lab/input_time.py, tests/unit/input_time_test.py
Hello!Created a time picker component, working also on input_timerange component
=> Adding time picker component

solara/components/select.py
dense option was hard coded to False in SelectMultiple component. I think it is a mistake. I've changed it so that the dense option can be passed to reacton.
=> fix: SelectMultiple is not using dense option

solara/components/head_tag.vue, solara/website/pages/documentation/getting_started/content/04-tutorials/60-jupyter-dashboard-part1.py, solara/widgets/vue/navigator.vue
The insertion of `<span></span>` into the dom is what causes strange extra spacing at the top of notebook-based tutorials with solara.Meta tags currently:
Fixes #626 
TODO:
=> fix!: solara.Meta elements insert empty span into DOM

solara/_stores.py, solara/hooks/use_reactive.py, solara/toestand.py, tests/unit/toestand_test.py
If the reactive variable return from use_reactive is set from outside a kernel_context, the reactive variable would not be set.
This bug is demonstrated in:
https://py.cafe/maartenbreddels/solara-shared-state
Where we had to force use_trait_observe to use use_state in of use_reactive.
=> fix: allow usage of use_reactive from outside kernel_context

solara/website/pages/documentation/advanced/content/30-enterprise/10-oauth.md, tests/integration/enterprise/oauth_test.py
Fief sunset Fief cloud, which we were using to support our tests, see [here](https://www.fief.dev/blog/a-new-step-in-fief-s-journey). Since supporting Fief is not a big priority right now, we mark it deprecated / unmaintained. As remarked in the docs, we aren't planning on removing support.
=> ci, docs: mark fief oauth support as unmaintained, disable test

solara/toestand.py, tests/unit/toestand_test.py
If a reactive variable was set from a different (or no) kernel context,
the event handler would not restore the kernel context that was
active when the event handler was registered.
Fixes https://github.com/widgetti/solara/issues/961
=> fix: restore kernel context on reactive event handler

solara/server/app.py, solara/test/pytest_plugin.py, tests/integration/starlette_test.py
https://github.com/widgetti/solara/pull/924 broke cases where solara was mounted in starlette or fastapi as a app, because the lifecycle method are not called in this case.
=> fix: automatically init app if not intialized yet

solara/cache.py
Type hints now make code editors happy when caching non-hashable function inputs (fixes #958)
=> fix: incorrect type hints on memoize `key` #958

solara/server/patch.py
We do this with all the other methods, so it makes sense to do it here as well. This should fix #965 and is an alternative to https://github.com/astropy/astropy/pull/17683
Easy way to test/confirm:
```
python -c "import solara.server.app; import astropy;
```
=> fix: get_ipython should dispatch to original if not in virtual kernel

solara/tasks.py, tests/unit/task_test.py
See https://github.com/widgetti/reacton/pull/42
Solara is already compatible with it, but the tests were not.
We might want to test this in CI, before releasing Solara 2.0
=> test: compatibility with reacton 2.0

solara/website/pages/documentation/components/lab/theming.py
Resulted in some confusion for me as to why the color change wasn't working when in dark theme
=> docs: emphasize having to set both theme variants for theme colors

solara/website/components/docs.py
The pages were linked to, but didn't exist
Fixes https://github.com/widgetti/solara/issues/802.
=> docs: add pages for subcategories

solara/server/assets/style.css
Fixes https://github.com/widgetti/solara/issues/691.
A visually breaking change to the way widgets are rendered. By default they get a margin as determined by `--jp-widgets-margin: 2px`, but I think in combination with Vuetify this is often unexpected.
Overall I don't think there would be very many cases where this would be worse than the current implementation.
In the end I think the underlying issue is that ipywidgets based components are quite difficult to style, since they don't accept a style argument like we usually use.
However, I get if we prefer to stick as close as possible to vanilla jupyter widgets settings, in which case we could do one of two other things:
* Use `solara.HTML(tag='img', ...)` in our Image component, as opposed to `ipywidgets.Image`
* Scope the change to just …
=> fix!: unexpected margins on widgets

solara/server/assets/style.css
Add missing CSS for `widget-box` that ensures overflow is correctly shown
=> fix: widget-box would hide overflowing content

solara/__init__.py, solara/components/__init__.py, solara/components/misc.py, solara/lab/__init__.py, solara/lab/components/__init__.py, solara/website/pages/documentation/examples/utilities/countdown_timer.py
Fixes https://github.com/widgetti/solara/issues/950
Fixes https://github.com/widgetti/solara/issues/465
=> chore: explicitly re-export components

solara/__init__.py, solara/hooks/use_thread.py, solara/lab/__init__.py, solara/tasks.py, solara/util.py, solara/website/pages/__init__.py, solara/website/pages/documentation/api/hooks/use_task.py, solara/website/pages/documentation/api/hooks/use_thread.md, solara/website/pages/documentation/api/hooks/use_thread.py, solara/website/pages/documentation/api/utilities/task.py
Deprecate `use_thread` in favour of `use_task` and `Task`.
Closes https://github.com/widgetti/solara/issues/784
=> feat: deprecate use_thread

solara/server/patch.py, tests/unit/matplotlib_test.py
Our .clear on RcParams was working, while matplotlib was a no-op:
https://github.com/matplotlib/matplotlib/issues/25855
We now mirror this behavior.
Fixes #606
=> fix: mirror matplotlib bug in our virtual kernel patch

solara/website/pages/__init__.py
We remove the old style
```python
with solara.Element() as main:
...
return main
```
since the return would skip any components not inside `main`.
=> docs: twitter/og meta tags weren't present on most pages

solara/components/dataframe.py, solara/components/file_drop.py, solara/website/pages/documentation/examples/ipycanvas.py
This can trigger pytest failures in situations where warnings are considered errors.
cc @rosteen
=> fix: do not call use_side_effect, which is deprecated

.github/workflows/test.yaml, solara/test/pytest_plugin.py
=> fix(pytest-ipywidgets): support pytest-playwright 0.7.0

solara/server/kernel_context.py, solara/tasks.py, tests/unit/task_test.py
Instead of assuming an event loop to exist, we use the event loop of the main thread in solara server (the one that starlette created for the websocket).
In the case of IPython/Jupyter, we use the main event loop.
=> fix: allow calling async tasks from threaded tasks

solara/server/kernel.py, solara/server/starlette.py, tests/integration/lifecycle_test.py
There was one more runtimeerror we had to catch, and also during
closing the websocket we could have expected errors.
Fixes https://github.com/widgetti/solara/issues/1013
=> fix: correctly handle expected websocket errors instead of logging

solara/server/starlette.py
We assumed when the text or bytes were None that it was a missing value, but on Modal we do see a message like that, e.g.:
{'type': 'websocket.receive', 'bytes': b'...', 'text': None}}
See https://asgi.readthedocs.io/en/latest/specs/www.html#receive-receive-event which explain that None and missing are equivalent.
=> fix: follow asgi spec and also check if text or bytes are None (Modal fix)

solara/test/pytest_plugin.py
Small PR - evaluates the port as port of the runtime error when server is running
=> fix: display port in runtime error when server is running

solara/widgets/vue/gridlayout.vue, solara/widgets/widgets.py
This PR adds an optional `on_layer_updated` trait to GridLayout which can be used to handle the event when the layout finally changes (i.e. when the "drag" of the items has ended). This could be desirable (see #1040) to use instead of the `on_grid_layout`, which triggers the event for every change when the drag is still ongoing.
=> feat: add `on_layout_updated` to GridLayout

solara/components/file_browser.py, tests/unit/file_browser_test.py
cc @kecnry @rosteen 
This should resolve the issue in jdaviz where you go two directories up
=> fix: FileBrowser could go two directories up if ".." was selected

solara/server/server.py, solara/server/settings.py
Use it like:
```
SOLARA_THEME_TITLE="foobar" solara run sol.py
```
=> feat: configure the initial title before the app runs/loads
