widgetti/solara

packages/assets/RELEASE.md, packages/assets/hatch_build.py, packages/solara-widget-manager/src/manager.ts, solara/__main__.py, solara/server/app.py, solara/server/flask.py, solara/server/kernel.py, solara/server/patch.py, solara/server/pyodide.py, solara/server/reload.py, solara/server/server.py, solara/server/starlette.py, solara/server/static/main-vuetify.js, solara/server/static/solara_bootstrap.py, solara/server/static/webworker.js, solara/server/templates/loader-plain.html, solara/server/templates/loader-solara.html, solara/server/templates/solara.html.j2, tests/integration/conftest.py, tests/integration/error_test.py, tests/integration/reload_test.py, tests/integration/server_test.py
=> Refactor execution model

solara/server/kernel.py
See https://github.com/ipython/ipykernel/pull/973
=> feat: support comm package

.github/workflows/integration.yml, solara/components/__init__.py, solara/components/download.vue, solara/components/file_download.py, solara/website/pages/api/__init__.py, solara/website/pages/api/file_download.py, tests/integration/file_download_test.py, tests/unit/file_download_test.py
=> feat: Download component to allow users to download data to a file

.github/workflows/integration.yml, .github/workflows/javascript.yaml, .github/workflows/unittest.yml, packages/solara-vuetify-app/package-lock.json, packages/solara-vuetify-app/package.json, packages/solara-vuetify-app/src/solara-vuetify-app.js, packages/solara-vuetify-app/webpack.config.js, packages/solara-widget-manager/package-lock.json, packages/solara-widget-manager/package.json, packages/solara-widget-manager/webpack.config.js, pyproject.toml, solara/server/app.py, solara/server/assets/style.css, solara/server/patch.py, solara/server/server.py, solara/server/templates/solara.html.j2
Although in the frontend we still use ipywidgets v7, most thing we do
do not care about this.
=> feat: support ipwidgets v8

solara/website/pages/docs/content/10-howto/20-multipage.md
`solara_test_portal` > `solara_test_portal.pages`
=> docs: update run command for `solara-test-portal`

solara/website/pages/api/use_thread.py
Assuming this is no longer needed
=> docs: remove `cancelled` arg from work function

solara/autorouting.py, solara/components/applayout.py, solara/server/assets/style.css, solara/server/static/main-vuetify.js, solara/server/templates/solara.html.j2, solara/website/pages/__init__.py
This gives a visual cue that the page is loading.
TODO:
=> feat: fade animation when navigating

solara/website/pages/docs/content/10-howto/20-multipage.md
updated call to run created portal 
(was mentioned correctly above)
=> correct call to run portal

solara/website/pages/api/use_state.py
=> mistake in docs title

solara/website/pages/examples/libraries/ipyleaflet.py
Related to: https://github.com/widgetti/solara/issues/264
=> website: added on_bounds to leaflet example

solara/components/togglebuttons.py, tests/unit/toggle_button_test.py
Fixes issue https://github.com/widgetti/solara/issues/231. Covers both `ToggleButtonsSingle` and `ToggleButtonsMultiple`.
=> feat: add attribute `mandatory` for ToggleButtons

solara/website/pages/examples/general/live_update.py
After discussion on discord with @maartenbreddels here is an example of how to set up a live updating component in solara
=> Add live update example to docs

solara/website/pages/docs/content/30-deploying/20-cloud-hosted.md
as discussed with @maartenbreddels, I'm adding Ploomber Cloud as a hosted option to the docs.
=> adds ploomber cloud as hosted option

solara/website/pages/docs/content/04-tutorial/40-streamlit.md
Fixed a typo on line 13
`solara/tree/master/solara/website/pages/docs/content/04-tutorial/40-streamlit.md`
=> fix(Update 40-streamlit.md): fixed a typo

solara/components/input.py, tests/unit/input_test.py
The hook is now much more legible, and lends itself to more generic use cases.
=> feat: Improved and generalized `_use_input_numeric`

solara/website/pages/docs/content/30-deploying/10-self-hosted.md
Add minimal solara template to the documentation
=> Add minimal solara template to the documentation

solara/test/pytest_plugin.py, solara/website/pages/docs/content/10-howto/50-testing.md
This can be useful when using parametrized tests.
=> feat(testing): support passing local variable to kernels

solara/server/templates/loader-solara.html
Using vue3, this was shown in the browser console
=> fix: vue transitions should use v-else, not two v-if's

solara/website/pages/api/__init__.py, solara/website/pages/api/use_effect.md, solara/website/pages/api/use_effect.py, solara/website/pages/api/use_memo.md, solara/website/pages/api/use_memo.py, solara/website/pages/api/use_thread.md
Added documentation for `use_effect`, `use_memo`, and improved the documentation of `use_thread`
=> docs: added documentation for hooks

solara/website/assets/custom.css, solara/website/components/mailchimp.py, solara/website/components/mailchimp.vue, solara/website/pages/__init__.py, solara/website/pages/docs/content/04-tutorial/60-jupyter-dashboard-part1.py, solara/website/templates/index.html.j2
refactor: MailChimp Integration
feat: Added mailing list on home page
=> refactor: MailChimp Integration

solara/website/pages/__init__.py
Less of a solution, more of a band-aid
=> fix: navigationdrawer behaviour on solara.dev

solara/website/templates/index.html.j2
Step 1: Added GTM tag. We can remove GTAG once we finish migration in the GTM client.
=> chore: migrating from gtag to gtm step 1

packages/solara-enterprise/solara_enterprise/cache/base.py, solara/cache.py
=> fix: mark hash key use as not used for security

solara/website/pages/docs/content/04-tutorial/60-jupyter-dashboard-part1.py
=> fix: use smaller webp format for images in tutorial 1

solara/toestand.py
This makes it easier to re-use the code for for instance a
computed reactive variable.
=> refactor: make a base class for reactive auto subscribe context manager

solara/toestand.py, tests/unit/toestand_test.py
Before, we would listen to both the ref and the parent reactive variable.
=> Fix: tracking ref double counts

solara/server/assets/style.css
This is caused by reset css of Vuetify
=> fix: page scrollbar always visible

pyproject.toml, solara/server/app.py, solara/server/esm.py, solara/server/patch.py, tests/integration/esm_test.py
This monkey patches ipyreact to create modules and import maps per
virtual kernel.
=> feat: support ipyreact / esm

solara/server/patch.py
Not every thread will use the run method (it may inherit and override).
Instead, _bootstrap will always be used.
=> fix(server): patch Thread._bootstrap instead of Thread.run

solara/lab/components/theming.vue
Fixes https://github.com/widgetti/solara/issues/528
=> fix: ThemeToggle becoming invisible against "primary" background

solara/hooks/misc.py, solara/lab/components/__init__.py, solara/lab/components/theming.py, solara/website/components/header.py, solara/website/pages/api/__init__.py, solara/website/pages/api/use_dark_effective.py, solara/website/pages/api/use_trait_observe.py, solara/website/pages/apps/scatter.py
Makes it easy to observe traits, and the example application of this
is use_dark_effective.
=> feat: add use_trait_observe and use_dark_effective

solara/util.py, solara/website/pages/apps/scatter.py
The scatter example now looks like:
[Following the link "Edit this example live on py.cafe"](https://app.py.cafe/snippet/solara?c=H4sIAP9V%2FGUC%2F61YbW%2FbNhD%2BK5z6RR4Ux%2B36KYCArmkDFCi6Ygk2DFEg0BIlc6VIjqQSa0X%2B%2B%2B4oyZZk2UmDOUFikce74708d6fvQaZyFlyQgFdaGUc0dRvB14nsnm1jE1kYVRHXaC5L0q3%2Fph1XkoqIZNS6RO4OaCpzagn86nywbJWghk4el2yrDbOeul1J9ZaQV8TyisMjcYpooZxoSEcZkXXtSKYqZskDdxuSGQXnCy4cM3bKXtB1p3y3AAe1kkw6C19FXUnb3%2BeyfTxKDhJYmhul%2BwNXsPABnvGOJWhSr9PaCBL3Z2vHxXK%2FEaapZ5EuQMkCzbrUgrpCmYr8FJMkYJXNDNeOySS4SCSBj24yWrAZtvuNEP0Vd05bfoX%2Fe0ERMeyfmhtW4Q3i2yTonBBEIK%2F1U%2Ffd2zgJ7kA5Jiybk%2F8FDJHIvEgtrbRgsKLzpWE0TzN7HybBxjltL87PDX3orl1bZjIl4UYOLXneSjnPqaOWOXteQeAwc15SXXGZM%2FMBNq74PfuLUbMEpkmwQOMmMhMUfHztqOs1s%2FxfllZ0u7cLaJI5OBy%2BXS1Xiz3VDAUGbNjH76115i7yt1t0xyAylHnBue0LzjQvOCNUOSfqioLn9iTNEyR5 …
=> feat: link to pycafe for editable live example

solara/website/components/header.py, solara/website/components/sidebar.py, solara/website/pages/__init__.py, solara/website/pages/changelog/__init__.py, solara/website/pages/contact/__init__.py, solara/website/pages/documentation/__init__.py
Should also fix an issue where sidebar would be completely absent after zooming in and back out
=> refactor(docs): use only route.module.Sidebar for website

solara/website/pages/documentation/getting_started/content/04-tutorials/60-jupyter-dashboard-part1.py
Under the hood this was caused by https://github.com/widgetti/solara/issues/626. But since the proper solution is potentially breaking, we are saving it for Solara 2.0
=> fix[docs]: remove extra space from top of jupyter dashboard tutorial

solara/server/templates/solara.html.j2
=> fix: markdown and ipywidgets themed css not being correctly loaded

tests/integration/input_date_test.py
Instead of running the tests on today and tomorrow, let's fix them to a particular date.
=> fix(ci): test_input_date_range failing on last day of the month

solara/components/switch.py
Bypass the color property of the solara.Switch component to the vuetify Switch.
=> bypass switch color to vuetify

solara/components/markdown.py
either that or was written by a dutch person
=> style: typo in NameError message

solara/server/assets/style.css
Originally this CSS was removed in eaade242f330228dd76793dc292a08dce5786b39 to improve performance.
Fixes https://github.com/widgetti/solara/issues/677
=> fix: ipywidgets accordion content not hidden when accordion is closed

solara/components/markdown.py, solara/website/components/sidebar.py, tests/integration/api_test.py, tests/integration/server_test.py
We did not have a node in the sidebar for the quickstart, which made me realized we were missing some pages.
=> Fix: docs navigation

solara/server/server.py
Fixes https://github.com/widgetti/solara/issues/714
=> Fix bug in server.py glob iteration by skipping directories

solara/__init__.py, solara/checks.py
Discovered in https://github.com/jupyter-widgets/ipyleaflet/issues/1034
=> fix: ipyleaflet extension is now called jupyter-leaflet

solara/website/components/algolia_api.vue
- fixes a bug where the results box would show that a negative number more results exist
- Keyboard navigation for results
=> docs: usability improvements to docs search

solara/website/components/algolia_api.vue, solara/website/components/contact.py, solara/website/pages/home.vue
docs: fix homepage styles broken when using SSG
feat: improve contact form
Adds feedback on success, checking if required fields were filled in, and shortens the time that snackbars are open
=> docs: fixes and improvements to documentation pages

solara/website/pages/home.vue
Primarily:
- fixes to mobile styling
- fixes for Safari / iOS
=> docs: fixes to styling

solara/website/pages/documentation/advanced/content/15-reference/41-asset-files.md
related to: https://github.com/widgetti/solara/discussions/710
=> docs: elaborate PNG/SVG clash of favicons

solara/website/pages/documentation/getting_started/content/04-tutorials/_jupyter_dashboard_1.ipynb
I fixed the url in the tutorial called Build your Jupyter Dashboard uisng Solara.
=> docs: fix broken link to cvs file in Jupyter  tutorial 

solara/server/assets/style.css, solara/website/pages/documentation/advanced/content/20-understanding/40-routing.md
We also start using this on our documentation site.
=> docs: explain how to make scrolling to an anchor smooth

solara/components/component_vue.py
Closes https://github.com/widgetti/solara/issues/825
=> Updated vue widget decorator to always use absolute template file path

solara/website/pages/documentation/examples/libraries/altair.py, solara/widgets/vue/vegalite.vue
Changing the renderer to svg as suggested in https://github.com/vega/react-vega/issues/85#issuecomment-657120539.
=> feat: support automatic resizing of altair/vega-lite figures

solara/website/pages/documentation/examples/utilities/countdown_timer.py
Update a new way of code in countdown_timer.py
=> update code in countdown_timer.py

.ci-package-locks/code-quality/python3.8.txt, .ci-package-locks/integration-vue3/osubuntu-ipywidgets8.txt, .ci-package-locks/integration/osubuntu-python3.8-ipywidgets7.txt, .ci-package-locks/integration/osubuntu-python3.8-ipywidgets8.txt, .ci-package-locks/integration/oswindows-python3.8-ipywidgets7.txt, .ci-package-locks/integration/oswindows-python3.8-ipywidgets8.txt, .ci-package-locks/pyinstaller/osmacos-python3.10.txt, .ci-package-locks/pyinstaller/osubuntu-python3.10.txt, .ci-package-locks/pyinstaller/oswindows-python3.10.txt, .ci-package-locks/unit/osmacos-python3.6-ipywidgets7.7.txt, .ci-package-locks/unit/osmacos-python3.9-ipywidgets7.7.txt, .ci-package-locks/unit/osmacos-python3.9-ipywidgets8.0.txt, .ci-package-locks/unit/osubuntu-python3.6-ipywidgets7.7.txt, .ci-package-locks/unit/osubuntu-python3.9-ipywidgets7.7.txt, .ci-package-locks/unit/osubuntu-python3.9-ipywidgets8.0.txt, .ci-package-locks/unit/oswindows-python3.9-ipywidgets7.7.txt, .ci-package-locks/unit/oswindows-python3.9-ipywidgets8.0.txt, .github/workflows/test.yaml, packages/solara-meta/pyproject.toml, solara/components/markdown.py, solara/website/components/markdown.py, solara/website/pages/documentation/getting_started/content/00-quickstart.md, solara/website/pages/documentation/getting_started/content/01-introduction.md
=> docs: use mkdocs-pycafe to include links to pycafe

tests/integration/lifecycle_test.py
=> ci: disable flaky lifecycle test

solara/website/pages/changelog/changelog.md
This wasn't added by accident when 1.41.0 was released
=> Add changelog entry for 1.41.0

.github/workflows/test.yaml
=> ci: we did not test against vue 3.x

solara/components/misc.py
=> docs: V/HBox deprecation notices reference wrong replacements

.pre-commit-config.yaml, pyproject.toml, solara/components/datatable.py, solara/server/shell.py, solara/tasks.py
Support pre-commit v5, and bump repos we use
=> ci: migrate pre-commit config, bump repos

solara/server/kernel_context.py, tests/integration/memleak_test.py
Fix final issues with memory leaks test:
* There were sometimes (in flask) references to kernel contexts from dummythreads
* The RuntimeError we raised when attempting to close an already closed kernel context would keep a stack with reference to the context
* Playwright's trace would also keep references to some of the tracked objects at times
=> ci: fix and re-enable memoryleak test

.github/workflows/test.yaml, solara/lab/components/chat.py, solara/website/components/docs.py, solara/website/pages/documentation/examples/__init__.py, solara/website/pages/documentation/examples/ai/chatbot.py
I think this pattern originated from the times of use_thread, while now we can directly start the task when we get a new user message.
Pardon the unrelated, but related typing change, I was also making the example typesafe.
=> refactor: make chatbot example easier (using task instead of use_task)

solara/server/starlette.py
This makes #841 simpler.
Instead of giving an error, we do our best, but warn the user it is better to send from a different thread.
=> feat: allow sending websocket messages from the main event thread.

solara/server/kernel_context.py
=> fix: remove self import in kernel_context.py

solara/lab/components/chat.py
Especially when streaming responses this would result in quite a few classes on the element
=> fix: `.chat-box` class was added every rerender

solara/server/app.py, solara/tasks.py, solara/toestand.py, tests/unit/toestand_test.py
on_kernel_starts would not always trigger after reloads.
Also task results would sometimes get lost on a reload.
=> Fix reload with tasks / on_kernel_start fix

solara/widgets/vue/gridlayout.vue, solara/widgets/widgets.py
Expose the `col-num` -> `col_num` and `row-height` -> `row_height` options for `GridLayout`.
=> feat: expose col_num and row_height options for GridLayout

solara/components/file_browser.py, solara/website/pages/documentation/components/input/file_browser.py, tests/unit/file_browser_test.py
=> feat: FileBrowser improvements

solara/server/starlette.py
Related to #1067
Added helper function _sanitize_for_json:
Detects infinite float/int values using math.isinf()
Converts them to None (which becomes null in JSON)
Returns other values unchanged
=> fix: sanitize infinite values in /resourcez JSON response
